export const EXAMPLE = 'EXAMPLE';
export const UPDATE_MONSTERS = 'UPDATE_MONSTERS';
export const UPDATE_ATTACKS = 'UPDATE_ATTACKS';
export const UPDATE_TEAMS = 'UPDATE_TEAMS';
export const UPDATE_ASSIGNMENTS = 'UPDATE_ASSIGNMENTS';

export const FETCHING_MONSTERS = 'FETCHING_MONSTERS';
export const FETCHED_MONSTERS = 'FETCHED_MONSTERS';
